@include('frontend.partials.head')
@include('frontend.partials.top-nav')
@include('frontend.partials.side-nav')
    @yield('content')
@include('frontend.partials.footer')
@include('frontend.partials.foot')
