<?php

namespace App\models\backend;

use App\models\frontend\BlogComment;
use App\models\frontend\BlogUser;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table = 'blogs';

    public function blogCategory()
    {
        return $this->hasMany('App\models\backend\BlogBlogCategory');
    }

    public function getRouteKeyName()
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub/
        return 'slug';
    }


    public function comments()
    {
        return $this->hasMany(BlogComment::class);
    }

    public function users()
    {
        return $this->hasMany(BlogUser::class);
    }
}

